name = "nav-dashboard"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "nav-dashboard-db"
database_id = "110c9d6b-52d7-4d2c-876b-1c6ba08f22d4"

# KV 命名空间绑定（用于图片存储）
[[kv_namespaces]]
binding = "KV"
id = "cb261e73c6414283a804222054699019"

# Pages 配置
pages_build_output_dir = "public"


